### ISSUE TITLE
Add Shadow Length [SHLN] axis

### ISSUE THREAD

**Issue by agyeiarcher** [googlefonts/axisregistry#122]
### Requirements

Before creating this new issue to propose a new custom axis, you should read the [Axis Registry Protocol](https://googlefonts.github.io/gf-guide/axis-registry.html) in the Production chapter of the GF-Guide. It provides the required steps for including a new axis (prior to creating this Issue), as well as detailed information on the axis requirements and the type of axes that would inform your decisions on the required Metadata Fields.

By ticking the cases (or putting x between the square brackets in text mode), you confirm the following:

- [x] I have inspected the current [Axis Registry](https://github.com/googlefonts/axisregistry/tree/main/Lib/axisregistry/data) and there is not a registered custom axis that could be used for the variation purpose on the upcoming font project.
- [x] The metadata fields of the proposed axis meet the *Axis Requirements* as specified in the Protocol (linked above).

### Font project(s) using the axis

https://github.com/agyeiarcher/Crispy-VF

### Short description of what the axis does

Adjusts the extrusion depth of shadow in a fixed direction for a variable font.

### Image

![image](https://im5.ezgif.com/tmp/ezgif-5-c5f02c1b5f.gif)

### Why is the axis needed

In the application of shadow axes for expressive typography, there may be need based on device size or intended effect to be able to either animate or have variable static instances of a shadowed font.

### Axis metadata fields

(Remove this line and fill out the mock of the data structure of the axis)

```
# SHDW based on https://github.com/agyeiarcher/Crispy-VF
tag: "SHDW"
display_name: "Shadow"
min_value: 1 
default_value: 1 
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 10.00
}
fallback_only: false
description: "Adjust the extrusion depth of a shadowed font"
````

**Comment by davelab6** [comment]
> `min_value: 1 `

I would expect min to be 0 so it can be turned off. 

Default of 10 is probably good, matches https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/extrusion_depth.textproto proportionally; but then, that axis might be reusable?

**Comment by kenmcd** [comment]
The average user is going to be more familiar with Shadow (used in many applications as a text effect).

Rocher Color (COLR) also has Shadow (SHDW):

![RocherColor-SHDW 2023-01-31_14-06-19](https://user-images.githubusercontent.com/844920/215896882-67eaaeec-9043-4d57-932b-f9729f238875.gif)

**Comment by yanone** [comment]
+1 for per mille of em-based units.
As [Honk](https://github.com/EkType/Honk) also needs this, I propose this update:

```
# SHDW based on https://github.com/EkType/Honk
tag: "SHDW"
display_name: "Shadow"
min_value: 0 
default_value: 0 
max_value: 1000
precision: -1
fallback {
  name: "Default"
  value: 0.00
}
fallback_only: false
description: "Adjust the extrusion depth of a shadowed font"
```

The max value is kind of arbitrary since it depends on each font's design decisions. There is no real limit here on how long a shadow could be. So it may have to be set higher, either right away or later.

The proposal above stated a default value of 10, but if shadow length is arbitrary and measured in em units, then there is no guarantee that 10 is even available. To be on the safe side, the default would have to be 0.

**Comment by davelab6** [comment]
Def 10 max 1000 is fine

**Comment by vv-monsalve** [comment]
Axis definitions reviewed today

### Name and tag

Display Name: `Shadow Depht`
Tag: `SHDP`

Registering the axis with a compound name would make registering other possible shadow-related axes easier in the future in a systematical way. E.g.  [`Shadow Rotation - SHRT` ](https://github.com/googlefonts/axisregistry/issues/147)

### Type and Range

A percentage axis will make it easier for users to interpret the effect of the axis, where 0% would have no shadow at all and 100% would be the total amount of shadow applied, which would be relative to each design. The absolute range tied to type units, while technically correct at design time, makes it more abstract for users to interpret. 

**Default**
A default value other than zero for displaying the font's shadow effect upon loading is the best practice. 
However, upon examining the Honk, the effect is hardly visible at the suggested 10 value. Since a single static font will be produced for the default position, a 50% value is recommended to ensure the shadow effect is noticeable from the start.

**Precision**
The precision could be set to `-1` to allow the relation to 1000 units. Similar to how the Spacing axis was defined.

````
min_value: 0 
default_value: 50 
max_value: 100
precision: -1
````
### Description

Proposal

````
  "Adjusts the font's shadow depth. From no shadow visible (0 %)"
  " to a maximum shadow applied (100%) relative to each family design."
````

**Comment by yanone** [comment]
I concur generally.

I just want to say that I've never heard anyone speak of a shadow’s depth. I would use the word length instead.

**Comment by vv-monsalve** [comment]
Then it could be:

### Name and tag

Display Name: `Shadow Length`
Tag: `SHLN`

**Comment by davelab6** [comment]
> I just want to say that I've never heard anyone speak of a shadow’s depth. I would use the word length instead.

Hmm, but you earlier posted, `description: "Adjust the extrusion depth of a shadowed font"` ;)

I would see Depth as a pure Y-dimension distance, and Length as the extrusion distance.

I guess I see per-mille values as most useful in pure X or Y dimensions, so if we do Length, a percent range could make more sense over a per-mille range, while per-mille would be better for a Depth distance - that is straight up/down from baseline, 
with up being a negative value. That being said, the `Extrusion Depth` axis introduced for Nabla is **very** similar, and I suspect that is both per-mille and really "extrusion length" in the context of the distinction being made here, with values measuring diagonal distances. 

If so, if we want to register this by itself without reference to Extrusion Depth, then I guess it would be `Shadow Length 0..100%`, but if we do want to form a system with Extrusion Depth, then I guess it would be `Shadow Depth 0..1000pm`. I'm fine with the solo option.

> To be on the safe side, the default would have to be 0.

However, we generally want to see the exemplar style as having some amount of shadow, so a default of 50% is fine, and there will always be a 50 value if the range is %.

**Comment by vv-monsalve** [comment]
@davelab6, please review the proposed description


````
  "Adjusts the font's shadow length from no shadow visible (0 %)"
  " to a maximum shadow applied (100%) relative to each family design."
````
