### ISSUE TITLE
Review the `MORF ` axis for the Honk font

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/axisregistry#151]
**Describe the issue**

The new `Honk` family could make use of the `MORF` axis but is [requesting a revision](https://github.com/googlefonts/axisregistry/pull/149) of the axis range and description.

**Comment by vv-monsalve** [comment]
Revisions done today at the meeting

**Range**

When defining axes, a range of 0 to 100 is typically used to represent percentages. A value of 0% indicates no modification, while 100% indicates the maximum or complete modification of the attribute being controlled. However, the 'MORF' axis is unconventional and cannot be interpreted in this way. It was defined with a time value range related to animation possibilities. The incoming Honk font does not have specific positions defined with named instances, so the current range can be used without modification.

If a higher range is needed, the precision value can be adjusted to add decimal places, or it could be increased up to a maximum of 120 to maintain the time association.

**Description**

It was determined that the current description should not limit changes in weight or width, so it needs to be made more universal.

Proposal

````
  "The letterforms change shape in unconventional ways, morphing" 
  " multiple attributes simultaneously. The axis incorporates a range of" 
  " 0 to 60, with each unit can be understood as a second, in relation" 
  " with animation possibilities."
````

**Comment by yanone** [comment]
I don't understand why a morph axis needs to be tied to seconds and I believe that this goes against the idea of defining universally applicable axes within GF for all future fonts to use.  

This axis definitely ties future fonts to the implementation that the first font using it intended. This is not what a universal axis registry was made for.

What a font does with a morph axis is completely arbitrary (_"unconventional ways"_) and therefore its values shouldn't be tied to any particular range or intention.

However, we can go ahead with your proposed changes as long as the range can be extended to 120. I feel like changing the font is unjustified just because an earlier font wanted to tie morphing to seconds.

And by the way, 100 seconds are a valid number of seconds. So really, the current morph axis is tied to minutes expressed as seconds, not seconds, if you propose 120 instead of 100.

And I find a percentage to be a much more acceptable unit for morphing than seconds. If you want to use seconds, an animation axis is the better target. Things can animate that aren't morphing.
The concept of morphing is to my knowledge not tied to any particular time frame such as this axis suggests.

> When defining axes, a range of 0 to 100 is typically used to represent percentages.

The description is used to explain how the values are to be interpreted. It can be a percentage, and it can be something completely different that also goes from 0 to 100 and isn't a percentage. Age, speed, really anything. I propose to not tie a value range from 0 to 100 to a percentage for all future use.

**Comment by vv-monsalve** [comment]
> This axis definitely ties future fonts to the implementation that the first font using it intended. This is not what a universal axis registry was made for.

The font originally introducing this axis did not have a defined range in seconds, only 1-4 values. After much discussion in several meetings, it was considered this axis is suitable for animations, @davelab6 was keen on using a time-based range so that it:
- had a broader range with meaningful semantics
- allows different fonts to use in the future
- and differentiating it from the 0--100 given this range implies the meaning of being complete or reaching a maximum level of a certain attribute. An interpretation that would be hard for something acting in random ways; thus, the time frame made more sense.

> What a font does with a morph axis is completely arbitrary ("unconventional ways") and therefore its values shouldn't be tied to any particular range or intention.

Which also applies to a percent range. Here and during the meeting, you mentioned that you don't want to change the current font implementation and that's why you suggest changing the axis range, which essentially would be tying the axis to the current font implementation, contradicting your initial objection to the current range. 

> However, we can go ahead with your proposed changes as long as the range can be extended to 120. I feel like changing the font is unjustified just because an earlier font wanted to tie morphing to seconds

As mentioned in previous comments and during this morning's meeting, the goal is precisely not to make per-registry level decisions tied to a font-level implementation. Sticking to the time sense at the registry level while allowing for flexibility in implementation at font level with a shorter range, we have considered increasing the registry to 120.

If the current font has 18 meaningful positions (when we inspected it didn't show any), we could even increase the maximum value up to 180. This would still keep it time-related and allow for consistent intervals of 10.

It is possible to review the definitions further, of course. But to ensure productive discussions, it's essential to avoid making assumptions and to acknowledge previous work done. The decisions are not taken lightly or oversimplified, which is why we hold meetings for the axis registry. Assuming we registered an axis based solely on initial font needs goes against one of the first principles established in the Axis Registry Protocol, precisely as a result of the work we have been doing.

> From selecting the axis name, tag, or description, to the type of range, it’s always necessary to find a balance between the current project demands and the further uses the axis could have. Thus, the reusability principle and keeping the end-user at the center of the decisions become essential to make it simpler and easier to understand, select and use the fonts and their axes.

**Comment by davelab6** [comment]
I’m not sure this is the right axis to reuse here, but if so, I don't accept changes to the range - 60 is a semantically important number base, and 120 or 180 or 1,234 are also valid numbers of seconds but not the number-base of time, so just 2x or 3x multiplications of the base. I expect to change any font that has this axis to use the full 0..60 range, if it doesn't already.

Supposing Honk has 11 named styles along the current Style axis, I would expect seeing those at 6 unit intervals, 0, 6, ... 54, 60.

**Comment by davelab6** [comment]
Ek Type agreed to use Honk as is, so I think we can close this.

**Comment by vv-monsalve** [comment]
Thank you. I was waiting to have an official confirmation on this. Closing it now.
