### ISSUE TITLE
Add Bleed (BLED) Axis

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/axisregistry#17]
Fonts to be onboarded that have this axis:
* https://github.com/google/fonts/issues/3425

**Comment by vv-monsalve** [comment]
Discussion opened in [#3697](https://github.com/google/fonts/issues/3697)

**Comment by RosaWagner** [comment]
Copy pasting Jens' issue here:

My [Homecomputer fonts](https://github.com/jenskutilek/homecomputer-fonts) use custom variation axes for visual artefacts related to [display on a cathode ray tube](https://www.masswerk.at/nowgobang/2019/dec-crt-typography): (horizontal) bleed (tag: BLED) and (vertical) scan lines (tag: SCAN).

I propose to add those axes to the Google Fonts axis registry:

## Bleed (BLED)

### On CRT screens

The horizontal "bleed" of the pixels on a CRT screen is caused by the phospor latency:

![VTterm-phosphor-flanks](https://user-images.githubusercontent.com/3185950/129218316-85144541-d21b-4476-ac0e-7279e4ea57a0.png)
(Source: VT100 Series Technical Manual, EK-VT100-TM-002, p. 4-78)

The "Homecomputer" fonts simulate this effect by elongating the edge pixels horizontally.

![Bildschirmfoto 2021-08-12 um 16 52 26](https://user-images.githubusercontent.com/3185950/129218734-86edf033-00a3-4e29-9e89-401fdc85d184.png)
BLED=0

![Bildschirmfoto 2021-08-12 um 16 52 30](https://user-images.githubusercontent.com/3185950/129218791-e5203a6d-a045-420c-9e54-42e2e4252302.png)
BLED=max

### Other uses

A _Bleed_ axis could also be used to simulate the bleed of ink on paper. This is distinct from the proposed [Grade axis](https://github.com/google/fonts/blob/main/axisregistry/grade.textproto), which adds or subtracts weight from the glyphs uniformly, whereas the _Bleed_ axis could add or subtract weight in a way simulating the distribution of ink on paper when the printing process uses little or too much ink or pressure.

![typewriter-jens-kutilek](https://user-images.githubusercontent.com/3185950/129222127-f974c9b2-f954-47ea-b821-978d895ac39c.jpg)
Ink bleed on typewritten text. Top row: various levels of added bleed due to differences in pressure applied to the keys of a mechanical typewriter. Bottom row: negative bleed due to typing without a ribbon and thus the color fading as a key is struck multiple times.

### Axis proposal

```
tag: "BLED"
display_name: "Bleed"
min_value: -1000
max_value: 1000
default_value: 0
precision: 0
fallback {
  name: "Normal"
  value: 0
}
description:
  "Add or subtract weight from strokes or other forms in a uniform, random,"
  " or logical way, without any changes overall width, inter-letter spacing,"
  " or kerning, so there are no changes to line breaks or page layout."
  " Negative bleed makes the style lighter, while positive bleed makes it bolder."
  " This can be used to simulate different levels of ink bleed on paper, as"
  " commonly found in printed or typewritten materials."
```

**Comment by RosaWagner** [comment]
The addition of this axis is still to discuss, because it could be a width axis

cc @davelab6

**Comment by vv-monsalve** [comment]
After the last revision, it was decided to include this axis in the axis registry as a [relative axis](https://googlefonts.github.io/gf-guide/axis-registry.html#relative-range-axes), with a percent range to allow for various implementations to be used in the future.

Two extra considerations

- [ ] **Axis name** confirmation. @jenskutilek Could `Dot Stretching` be a preferable name for the axis? Since it's the strategy employed to compensate for the phosphor latency issue. Otoh, would also be related to the [Dot Gain](https://en.wikipedia.org/wiki/Dot_gain) "which causes printed material to look darker than intended", relevant to the other use case given above.
In the CRT article, Bleed is referenced as added phosphor effect (some glow) rather than the dot-stretching the axis does. At the same time, in printing, the most common use of [Bleed](https://en.wikipedia.org/wiki/Bleed_(printing)) term refers to the extra area of color added beyond the edge expected to be trimmed (rather than the ink gaining).

- [ ] **Description** The description needs to be refined following the above.

Last metadata fields:

````
# Bleed, based on https://github.com/jenskutilek/homecomputer-fonts
tag: "BLED"
display_name: "Bleed"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
Description:
  "Modulates the darkness in the typographic color of strokes or other forms, without any changes overall"
  " width, inter-letter spacing, or kerning, so there are no changes to line breaks or page layout."
  " Negative bleed makes the style lighter, while positive bleed makes it darker. This can be used"
  " to simulate different levels of ink bleed or dot gain on paper, as commonly found in printed or typewritten materials."
````

**Comment by davelab6** [comment]
Description is a bit too long. How about:
```
 "Similar to Grade, this adjusts the overall typographic color without effecting"
  " line lengths or page layout. Negative bleed makes the style lighter, while"
  " positive bleed makes it heavier, as seen in the ink bleed or dot gain on paper,"
  " commonly seen in printed and typewritten materials."

**Comment by vv-monsalve** [comment]
I'm afraid saying "similar to grade" could bring some confusion or question like "why don't use grade then" when, as we talked, this would be almost an "anti-grade" axis (in the way it tries to achieve exactly the opposite grade tries to solve) :)

**Comment by davelab6** [comment]
Fair :)

    "Bleed adjusts the overall

**Comment by vv-monsalve** [comment]
But I agree it is too long. How about:

```
  "Bleed adjusts the overall darkness in the typographic color of strokes or other forms, without"
  " any changes in overall width, line breaks, or page layout. Negative values make the font appearance"
  " lighter, while positive values make it darker, similarly to ink bleed or dot gain on paper, commonly"
  " seen in printed and typewritten materials."
```
