### ISSUE TITLE
Add Scanlines (SCAN) Axis

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/axisregistry#18]
Fonts to be onboarded that have this axis:
* https://github.com/google/fonts/issues/3425

**Comment by RosaWagner** [comment]
Discussed in https://github.com/google/fonts/issues/3699

**Comment by RosaWagner** [comment]
The addition of this axis is still to discuss because it could be a weight axis.

cc @davelab6

**Comment by vv-monsalve** [comment]
After a recent review, it was decided to include this axis in the axis registry as a Relative axis, with a percent range instead of an absolute one. 
This decision was made because the current values used do not match any specific font measurement. Additionally, this change will make the axis more versatile and applicable to other scenarios where it can be used to adjust the number of lines (as in the example shown above), instead of the space between them. This change will allow for various implementations to be used in the future.

The description needs to be refined.

Definitive metadata fields:

````
tag: "SCAN"
display_name: "Scanlines"
min_value: -100
max_value: 100
default_value: 0
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "Segment glyphs horizontally without any changes overall width, inter-letter spacing,"
  " or kerning, so there are no line breaks or page layout changes. Negative values"
  " cause the glyphs to become visually segmented, while positive values may cause
  " the segments even overlap and create a bold effect."
````

**Comment by jenskutilek** [comment]
How about this?

```
description:
  "Break up shapes into horizontal segments without any changes in overall width, inter-letter spacing,"
  " or kerning, so there are no line breaks or page layout changes. Negative values"
  " cause the glyphs to become visually segmented, while positive values may cause
  " the segments to overlap and create a bold effect."
```

I don't know how specific the description has to be. Should it be mentioned that the segments could be rectangular, but may also take on other forms, like in the rounded lines image, or even be irregular in shape as long as they create the impression of a vertical segmentation?

**Comment by vv-monsalve** [comment]
> I don't know how specific the description has to be.

This level of definition sounds good. The description has to be clear and universal enough at the same time. So it doesn't need to go that much into details, like specific shapes.
