### ISSUE TITLE
Add Spacing (SPAC) Axis

### ISSUE THREAD

**Issue by davelab6** [googlefonts/axisregistry#27]
In https://github.com/fonttools/fonttools/discussions/2564 @twardoch proposed this axis

**Comment by arrowtype** [comment]
I wanted to dig into a few questions around how tracking works in Adobe products, so here are a few points that may be of interest. This isn’t to say that a tracking axis should necessarily mirror the approach of Adobe, but simply a quick investigation of how tracking works in apps that most graphic designers are familiar with.

**Question: Does Tracking scale kerning in Illustrator or InDesign?**
Answer: No. It simply adds (or removes) an even amount of extra space to each glyph.

<img width="929" alt="image" src="https://user-images.githubusercontent.com/45946693/162019771-40060f15-fd04-4048-8d5c-b9dfb05b5f9b.png">

**Question: It looks like large tracking values produce imbalanced spacing. How should a user address that?**
Answer: A user needs to either manually kern the result or change to `Optical` kerning.

<img width="866" alt="image" src="https://user-images.githubusercontent.com/45946693/162023229-36a9f4c9-bab6-4d71-8e50-63f602f99a6f.png">

**Question: Does tracking vary between different glyph pairs, e.g. HH vs VA? What about for word spaces?**
Answer: No. An even amount of extra space is added to each glyph, including the `space` glyph.

<img width="1405" alt="image-2" src="https://user-images.githubusercontent.com/45946693/162020420-aee57fef-eef1-42c2-b76c-4976b25c840c.png">

<img width="875" alt="image-4" src="https://user-images.githubusercontent.com/45946693/162020792-1a23168e-3bd3-46c1-9c09-77c8aa94222b.png">

**Question: _where_ is the extra space added? Is it to each side of each glyph, or to the left/right?**
Answer: Illustrator adds space to the right side of glyphs, at least in a left-to-right script. This helps make it easy to align text boxes on a grid, even if they have different amounts of tracking. However, if a `TRAK` axis is added to a variable font, I believe that added spacing should be added to both sides of each glyph – otherwise, it would be very difficult for users to center-align text that has added tracking.

<img width="818" alt="image-5" src="https://user-images.githubusercontent.com/45946693/162020975-8c32b80c-ca87-4b44-a5ad-b5d4fe64af88.png">

**Question: InDesign has a different text engine than Illustrator and Photoshop (which share an engine). Does InDesign handle tracking differently?**
Answer: Not really. InDesign does handle text boxes differently, though. 

<img width="910" alt="image-6" src="https://user-images.githubusercontent.com/45946693/162021943-393e3543-867a-45c8-921f-f41a0c062746.png">

<img width="1405" alt="image-7" src="https://user-images.githubusercontent.com/45946693/162022082-6bc2cb75-f0ff-4ca2-bb3e-f36691a7eb8e.png">

InDesign is a little more clever about not showing tracking added to the right of the final glyph (if, for example, you fit the text frame to content), but inDesign generally handles text boxes a little differently than Illustrator, so it’s a little hard to compare the apps 1-to-1.

<img width="786" alt="image-8" src="https://user-images.githubusercontent.com/45946693/162022191-1d29e9b6-86f0-4958-b0df-c02255c5c613.png">

**Comment by arrowtype** [comment]
Discussion in another channel around this topic revealed an interesting split of two basic approaches to the idea of “tracking”:

1. “Calibrated” – when adding extra space between letters, a program could perhaps use some kind of algorithm (like optical kerning) to balance the resulting whitespace. This is more complex than one might imagine, however, because kerning doesn’t scale in a 1-to-1 fashion for different pairs of glyphs (see the `HVA` example above – in a tightly spaced font, `HV` can’t get too close before crashing, while `VA` must be kerned hard to match that ... but as soon as you add a bit of extra space, `HV` suddenly has a lot more whitespace than `VA`).
2. “Blunt” – adding an equal amount of distance to each glyph, disregarding the balance of whitespace.

Potentially, this distinction suggests a distinction of two variable axes with different names:
1. A “Spacing” axis could be a calibrated approach, carefully balanced by the type designer (or font build system).
2. A “Tracking” axis could be a blunt approach, simply adding equal margin to all glyphs.

**Comment by arrowtype** [comment]
Three more interesting observations:

1. Counter to my expectations, Optical kerning _adds_ space between `AD` in tracked-out text, in serif fonts. I would expect it to slightly reduce spacing, to visually balance whitespace. However...
2. The amount of kerning changed by optical kerning is the same, regardless of tracking. That is, Optical kerning is calculated at `tracking: 0`, and not adjusted or calculated according to specific tracking. It makes sense, then, that `AD` is given extra space, because the algorithm is avoiding crashes/overlap at normal spacing. 

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/45946693/162031963-bef977f8-e7a5-459b-a495-326b75cbcf4c.png">

3. Optical kerning does change behavior for different font sizes. Most notably, it essentially adds tracking for smaller font sizes. This is similar to what a type designer would do for smaller optical sizes of a typeface. However, even at small sizes, Optical kerning takes the strategy of avoiding serif crashes. (I personally think that balancing whitespace volume is more important than avoiding crashes at small sizes while avoiding crashes is more important at large sizes.)

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/45946693/162033346-cdcfca50-e1c9-4a4a-b940-20071d145d1c.png">

**Comment by RuixiZhang42** [comment]
Let’s not limit ourselves to Adobe products…

In the TeX world, tracking is supported by pdfTeX, XeTeX, and LuaTeX. The last two also support OpenType.

### XeTeX/LuaTeX versus Adobe

#### The similar

Tracking is applied *uniformly* and *additively* on top of existing letter-spacing and existing kerning.

![tracking1](https://user-images.githubusercontent.com/39968857/162245650-0a7ae155-14d9-4246-87b4-5cfa49662513.png)

#### The (big) differences

1. In XeTeX/LuaTeX, tracking is applied between adjacent *glyphs* (not between adjacent characters) in a *glyph run* (aka, a word, a cluster). For example, the glyph run `Tofirefly` normally consists of 7 glyphs: `T`, `o`, `/f_i`, `r`, `e`, `/f_l`, `y`. This gives 6 spots to insert tracking.

   Since this approach is glyph-based, XeTeX and LuaTeX don’t break apart ligatures (automatically) when tracking.

   ![tracking2](https://user-images.githubusercontent.com/39968857/162259326-69bc9a33-9403-4237-bdcd-189d24eb191f.png)
2. TeX doesn’t treat `/space` as a character (or a glyph), and this is where TeX and Adobe (or CSS) behaves very differently.

   In `HH HH`, Adobe will insert tracking *after* every letter (including the `/space` character), effectively making a new “space” that is two-tracking wider than the original “space”. XeTeX and LuaTeX only see two glyph runs, and insert tracking *only within each glyph run*; no tracking is inserted after the last glyph of each glyph run. XeTeX and LuaTeX will also add the tracking amount to the original width of the `/space`, effectively making a new “space” that is only one‍-tracking wider than the original “space”.

   ![tracking3](https://user-images.githubusercontent.com/39968857/162263452-d2fd159c-9de6-4ff9-bf18-7a27e3b67b2c.png)

**Comment by arrowtype** [comment]
Do we need to complete this issue before I can successfully master a font for Google Fonts, using this axis?

**Comment by dberlow** [comment]
Have you made a vf that demonstrates this?

On Jun 22, 2022, at 7:50 AM, arrowtype ***@***.***> wrote:

﻿
Do we need to complete this issue before I can successfully master a font for Google Fonts, using this axis?

**Comment by arrowtype** [comment]
It would depend how strict of criteria you'd be judging by, but yes, I believe so.

Please see the type tester section of this, if you want. The "tracking" field controls a TRAK axis in the font. The font isn't publicly available yet, but feel free to download the woff2 file if you'd like to.

https://next--shantell-sans.netlify.app/

**Comment by dberlow** [comment]
I’ve been working to try and define a variable solution to a “spacing” axis for a while. During that continuing exploration I wrote this;  the type designer spaces and adds kerning pairs to reduce the likelihood of the word space being confused with the space between two letters, there’s also another kind of Kerning called latent Kerning that I never heard of called that until I started needing to call it something. Latent Kerning is in pairs of letters like LA, TT, or L with almost all Lowercase, that, as result of their combination, leave space we’re used to.
This Kerning is latent, as in its default form the spaces are made invisible by combination of good spacing and Kerning on the part of the type development, and the reader being more than used to these spaces, they are part of word recognition. But graphically they are wrong, There could be more space taken out of them which tends to show up when you add more space around them. 

Where the latent Kerning in type starts to show, is when tracking and letter spacing are used for whatever purpose. While many mainstream fonts appear immune to this, there are also many typeface families that could benefit from a systematic way of handling this in composition, so that spacing or tracking would be applied proportionally I sted of mathematically equal on each pair, regardless of Kerning or not.

Suspected, external exacerbators Include tracking and use the sizes inappropriate to the design of a style.￼

Suspected internal exacerbators Include the weight and width of the style, the relationship to the lowercase and uppercase￼ heights, and the range of contrast among the widths of the glyphs of each case.

So I guess what I’m interested in “GPOV” storage of values that are portional to the amount of sidebearings of the glyphs to begin with… as tracking round and square sided glyphs rapidly despaces them:
![1CF2FDFA-9D86-4577-BCFD-C623CE992207](https://user-images.githubusercontent.com/1956494/175102687-fee1dd86-97dc-4038-bc81-ced5e207614e.jpeg)
No matter how cool the font!

…and after that handle whatever latencies there are about exceptional pairs, which probably means tracking them at a different rate.

**Comment by kenmcd** [comment]
> Please see the type tester section of this, if you want. The "tracking" field controls a TRAK axis in the font. The font isn't publicly available yet, but feel free to download the woff2 file if you'd like to.
> 
> https://next--shantell-sans.netlify.app/

Is there a place I can post some issues found with the TRAK axis?
I know the repository is still private,
And it does not seem appropriate to post here.
Or is development not yet to the point of issue posts being appropriate?

**Comment by nicksherman** [comment]
I was referred to this thread today because I just released an update to my [HEX Franklin](https://www.futurefonts.xyz/hex/hex-franklin) type family that includes a variable font with two spacing-related axes:
- “Tyght” tightens spacing at a different rate for each glyph / kerning pair
- “Not Touching” lets the user to control how much overlap is allowed between certain glyph pairs, if any.

There’s also a width axis.

One of the main motivators for making this was to allow designers more control over tight spacing in environments like the web where manual user kerning adjustments are impractical – the kind of kerning adjustments that are otherwise normally needed when applying typical all-glyphs-tightened-equally tracking (or `letter-spacing` in CSS).

It’s still basically just a proof of concept, but you can see how it works on the interactive demo page:
https://hex.xyz/HEX_Franklin/Tyght/

![HEX_Franklin-Tyght-variable](https://user-images.githubusercontent.com/1265313/176552370-4e8a60a1-2110-484c-9849-02caa130d73d.gif)

For what it’s worth, I don’t believe the term “tracking” should be used for any spacing mechanism that applies different amount of space to different glyphs. For starters, it would be changing the meaning of a term that is already very much established. But also, it can be helpful to have an option for uniform space adjustment _in addition to_ other non-uniform spacing mechanisms …

For example: with the HEX Franklin Tyght font, I will sometimes crank the Tyght axis waaaay down to get the most consistent inter-glyph clearances possible, but then add in a touch of uniform positive tracking – making things slightly less tight while maintaining the same rigid consistency of inter-glyph clearances. If I were to loosen the spacing with the Tyght axis alone, the clearances between some glyph pairs would start to diverge more than from other pairs.

**Comment by arrowtype** [comment]
@kenmcd Thanks for wanting to share some issues!

> Is there a place I can post some issues found with the TRAK axis?
> I know the repository is still private, and it does not seem appropriate to post here.
> Or is development not yet to the point of issue posts being appropriate?

It's not so much that development isn't to the point of issue posts being appropriate, but more that we don’t want to publish this typeface early.

If you’d like to share issues, please email me at stephen at arrowtype dot com 

Thanks!

**Comment by arrowtype** [comment]
> Latent Kerning is in pairs of letters like LA, TT, or L with almost all Lowercase, that, as result of their combination, leave space we’re used to.
> This Kerning is latent, as in its default form the spaces are made invisible by combination of good spacing and Kerning on the part of the type development, and the reader being more than used to these spaces, they are part of word recognition. But graphically they are wrong, There could be more space taken out of them which tends to show up when you add more space around them.

@dberlow Interesting observations and good points!

I’m unsure if you are arguing that a Tracking axis should require kerning specific to various tracking values.

Specific kerning could definitely be useful – and it’s likely even more vital for _negative_ tracking. It should certainly be _possible_ to adjust kerning along a Tracking axis.

However, I feel strongly that there should be no _requirement_ for kerning to be adjusted along a Tracking axis. A strength of axes like Weight, Width, and Optical Sizing is that they specify a general system of units to label a design axis, but they don't get overly prescriptive in how a designer must handle these axes. 

For example, the Weight axis doesn’t specify that there must be a source of shaping and kerning at “Regular,” even though this is a common practice and often helpful. It doesn’t specify certain stem widths or surface area percentage for a given weight, even though designers may wish to base this on popular designs. 

The flexibility is helpful, as it allows for a wider variety of type to be created, with a wider variety of approaches.

> ... tracking round and square sided glyphs equally, rapidly despaces them ... No matter how cool the font!

I would argue that the style of font _does_ matter significantly to how visible the “despacing” effect is. It is much easier for the eye to consider and judge spacing in a geometrically simple system like a sans serif than in a more complex system like a serif or display font.

It is of course possible that _your_ eye notices the despacing equally, regardless of a font’s style. But, you are a type designer with decades of experience, and as such, you have a much keener eye than most. This is great! However, not all projects have that timeline and budget, and arguably, perfection in spacing doesn’t matter equally in a marker font made specifically for animation and experimental usage vs e.g. a system UI font such as Roboto Flex.

---

Or, as @nicksherman argues...

> I don’t believe the term “tracking” should be used for any spacing mechanism that applies different amount of space to different glyphs. For starters, it would be changing the meaning of a term that is already very much established. But also, it can be helpful to have an option for uniform space adjustment in addition to other non-uniform spacing mechanisms …

Maybe an axis that changes inter-glyph spacing non-uniformly is distinct from “tracking,“ and should be given a distinct name.

Could “Spacing” work? 

By the way, Nick, I love how you’ve approached the Tyght and Not Touching axes! It looks like Tyght is basically a “Spacing” axis, correct? If you were to propose a more standard-sounding name, what might you call it?

**Comment by dberlow** [comment]
Spacing could work, but not as a user axis, as far as I can tell. 

Tracking in a font is not fully answered in @arrowtype's  
_Question: Does Tracking scale kerning in Illustrator or InDesign?
Answer: No. It simply adds (or removes) an even amount of extra space to each glyph._

True answer is that's it does, but it adds it all to the right when text is set flush left, to the left is set flush right, and equally on each side when text is centered, yes?

So, neither tracking, which is based on the glyph width, or spacing, which I want based on the side bearing width, are going to be able, without swinging the glyphs back and forth in their tracked or spaced unit, to inform any application of how to behave with the typical user options for line layout. 

Hex Franklin is demonstrating spacing on an edge of what such an axis can accomplish, though linespacing is not mentioned, but is required of the user. On this edge, only because the inter-glyph spaces are so very small, set flush left, right or centered, don't much matter.

But that demonstration is not showing the rest of a useful space axis, where, e.g. the same Hex Franklin design is functioning with idealized spacing at opsz6. I mean, the drawings would survive the smaller size well enough, and the spacing would become normal-looking at opsz 6, as opposed to either of Hex Franklin's spacing axes.

Beyond that, we've got to find out if Fontmake is efficiently handling the shifting of glyphs, or probably forget the whole thing. I.e. glyphs can shift in any direction based on the movement of one point per contour, with the rest of the glyph shifting via interpolation. While Fontmake is a reasonable black box to me, I've been told it evaluates variations between sources to determine the required gvars by region, which does not sound right for this, and is likely to leave a big footprint if not handled with something special, like a "shift glyph" function that minimizes the storage to one point per contour.

So, I need to create a space axis, and swing axis, and registered or not, here they come. Whether that leads to tyght, tight but not touching, overlapping or whatever, we'll have to work it out for a lot of scripts and designs before too long, I suspect.

**Comment by arrowtype** [comment]
> Tracking in a font is not fully answered in @arrowtype's
>> Question: Does Tracking scale kerning in Illustrator or InDesign?
>> Answer: No. It simply adds (or removes) an even amount of extra space to each glyph.

> True answer is that's it does, but it adds it all to the right when text is set flush left, to the left is set flush right, and equally on each side when text is centered, yes?

The tests I did led me to believe that kerning is not **_scaled_** when tracking is adjusted, in Adobe Illustrator & InDesign. If you disagree that this is the status quo for those apps, would it be possible to show visually why you think it is scaled?

![](https://user-images.githubusercontent.com/45946693/162019771-40060f15-fd04-4048-8d5c-b9dfb05b5f9b.png)

I agree that the _ideal_ is to kern a font for a given amount of tracking/spacing. My earlier question was just about what is currently done in common apps.

Though yes, it is significant that tracking adds space either to the right side, left side, or both sides, depending on text alignment. 

This would be somewhat tricky to do in a variable font axis, and (probably?) impossible in just one axis. So, for my current implementation of a Tracking axis, I do simply add space to both sides of each glyph. It isn’t ideal, but it seems like the best option. If spacing were only added to the right of each glyph, it would suddenly become impossible to center-align text, which may not be vital for a font intended for Swiss-style grid design, but is pretty vital for a "comic" style font.

### Efficiency

My current process for making a TRAK axis is to duplicate the base style UFO, then added margin evenly to both sides of every glyph. The designspace only requires one additional source this way (not doubling the other sources, as might be necessarily for a axis that changes shaping, like a Weight axis).

As for efficiency, I’m probably not the best person to answer this, but I’ve looked into it a little bit by comparing the full Shantell Sans VF to one with `TRAK` dropped (using the FontTools Instancer). Here are some observations:

- The TRAK axis adds only 7.4 KB in a font file that is about 2 MB.
- The difference is about 6.1 KB for after conversion to WOFF2.

<img width="352" alt="image" src="https://user-images.githubusercontent.com/45946693/177381088-4a936299-d8ac-43ec-9dc6-c58ad950d233.png">

I also used `ttx` to inspect the full VF’s GVAR table. The `TRAK` entries are much more concise than others, leading me to believe that a FontMake-based build _is_ being pretty clever about recording the repositioning differences efficiently. 

A variation record for `TRAK` at max only contains two entries, one for the first and one for the last point. By contrast, a record for `wght` at max contains an entry for each point (on and off curve). Additionally, there are more records for wght + each other axis, whereas `TRAK` is only recorded once.

As a concrete example, here is the entry for the `period`, which is a simple blobby shape:

<details>
<summary><b>Full GVAR entry for /period glyph</b> (Click to expand)</summary>

```xml
<glyphVariations glyph="period">
      <tuple>
        <coord axis="ital" value="1.0"/>
        <delta pt="0" x="-41" y="0"/>
        <delta pt="1" x="-41" y="0"/>
        <delta pt="2" x="-31" y="0"/>
        <delta pt="3" x="-25" y="0"/>
        <delta pt="4" x="-20" y="0"/>
        <delta pt="5" x="-15" y="0"/>
        <delta pt="6" x="-15" y="0"/>
        <delta pt="7" x="-15" y="0"/>
        <delta pt="8" x="-20" y="0"/>
        <delta pt="9" x="-27" y="0"/>
        <delta pt="10" x="-31" y="0"/>
        <delta pt="11" x="-34" y="0"/>
        <delta pt="12" x="-41" y="0"/>
        <delta pt="13" x="0" y="0"/>
        <delta pt="14" x="20" y="0"/>
        <delta pt="15" x="0" y="0"/>
        <delta pt="16" x="0" y="0"/>
      </tuple>
      <tuple>
        <coord axis="wght" value="1.0"/>
        <delta pt="0" x="52" y="-6"/>
        <delta pt="1" x="13" y="-6"/>
        <delta pt="2" x="-12" y="2"/>
        <delta pt="3" x="-12" y="30"/>
        <delta pt="4" x="-12" y="53"/>
        <delta pt="5" x="9" y="78"/>
        <delta pt="6" x="34" y="78"/>
        <delta pt="7" x="62" y="78"/>
        <delta pt="8" x="91" y="62"/>
        <delta pt="9" x="102" y="38"/>
        <delta pt="10" x="102" y="24"/>
        <delta pt="11" x="102" y="8"/>
        <delta pt="12" x="74" y="-6"/>
        <delta pt="13" x="0" y="0"/>
        <delta pt="14" x="90" y="0"/>
        <delta pt="15" x="0" y="0"/>
        <delta pt="16" x="0" y="0"/>
      </tuple>
      <tuple>
        <coord axis="IRGL" value="1.0"/>
        <delta pt="0" x="10" y="0"/>
        <delta pt="14" x="20" y="0"/>
      </tuple>
      <tuple>
        <coord axis="BNCE" value="-1.0"/>
        <delta pt="1" x="0" y="-61"/>
        <delta pt="2" x="0" y="-60"/>
        <delta pt="10" x="0" y="-61"/>
        <delta pt="11" x="0" y="-60"/>
      </tuple>
      <tuple>
        <coord axis="BNCE" value="1.0"/>
        <delta pt="1" x="0" y="61"/>
        <delta pt="7" x="0" y="61"/>
        <delta pt="8" x="0" y="60"/>
      </tuple>
      <tuple>
        <coord axis="TRAK" value="1.0"/>
        <delta pt="0" x="250" y="0"/>
        <delta pt="14" x="500" y="0"/>
      </tuple>
      <tuple>
        <coord axis="ital" value="1.0"/>
        <coord axis="wght" value="1.0"/>
        <delta pt="0" x="-14" y="0"/>
        <delta pt="1" x="-14" y="0"/>
        <delta pt="2" x="-13" y="0"/>
        <delta pt="3" x="-7" y="0"/>
        <delta pt="4" x="-3" y="0"/>
        <delta pt="5" x="2" y="0"/>
        <delta pt="6" x="2" y="0"/>
        <delta pt="7" x="2" y="0"/>
        <delta pt="8" x="0" y="0"/>
        <delta pt="9" x="-5" y="0"/>
        <delta pt="10" x="-8" y="0"/>
        <delta pt="11" x="-11" y="0"/>
        <delta pt="12" x="-14" y="0"/>
        <delta pt="13" x="0" y="0"/>
        <delta pt="14" x="-20" y="0"/>
        <delta pt="15" x="0" y="0"/>
        <delta pt="16" x="0" y="0"/>
      </tuple>
      <tuple>
        <coord axis="ital" value="1.0"/>
        <coord axis="IRGL" value="1.0"/>
        <delta pt="0" x="-10" y="0"/>
        <delta pt="14" x="-20" y="0"/>
      </tuple>
      <tuple>
        <coord axis="ital" value="1.0"/>
        <coord axis="BNCE" value="-1.0"/>
        <delta pt="8" x="-12" y="0"/>
        <delta pt="10" x="-12" y="0"/>
        <delta pt="11" x="-13" y="0"/>
      </tuple>
      <tuple>
        <coord axis="ital" value="1.0"/>
        <coord axis="BNCE" value="1.0"/>
        <delta pt="0" x="13" y="0"/>
        <delta pt="1" x="12" y="0"/>
        <delta pt="2" x="13" y="0"/>
        <delta pt="3" x="13" y="0"/>
        <delta pt="4" x="12" y="0"/>
        <delta pt="5" x="12" y="0"/>
        <delta pt="6" x="13" y="0"/>
        <delta pt="7" x="13" y="0"/>
        <delta pt="8" x="12" y="0"/>
        <delta pt="9" x="12" y="0"/>
        <delta pt="10" x="13" y="0"/>
        <delta pt="11" x="12" y="0"/>
        <delta pt="12" x="12" y="0"/>
        <delta pt="13" x="0" y="0"/>
        <delta pt="14" x="0" y="0"/>
        <delta pt="15" x="0" y="0"/>
        <delta pt="16" x="0" y="0"/>
      </tuple>
      <tuple>
        <coord axis="wght" value="1.0"/>
        <coord axis="IRGL" value="1.0"/>
        <delta pt="0" x="-40" y="0"/>
        <delta pt="1" x="-21" y="0"/>
        <delta pt="2" x="0" y="-3"/>
        <delta pt="3" x="0" y="-10"/>
        <delta pt="4" x="0" y="2"/>
        <delta pt="5" x="23" y="10"/>
        <delta pt="6" x="30" y="10"/>
        <delta pt="7" x="12" y="10"/>
        <delta pt="8" x="-10" y="18"/>
        <delta pt="9" x="-20" y="28"/>
        <delta pt="10" x="-20" y="32"/>
        <delta pt="11" x="-20" y="22"/>
        <delta pt="12" x="-30" y="0"/>
        <delta pt="13" x="0" y="0"/>
        <delta pt="14" x="-20" y="0"/>
        <delta pt="15" x="0" y="0"/>
        <delta pt="16" x="0" y="0"/>
      </tuple>
      <tuple>
        <coord axis="wght" value="1.0"/>
        <coord axis="BNCE" value="-1.0"/>
        <delta pt="0" x="0" y="49"/>
        <delta pt="1" x="0" y="49"/>
        <delta pt="2" x="0" y="47"/>
        <delta pt="3" x="0" y="49"/>
        <delta pt="4" x="0" y="48"/>
        <delta pt="5" x="0" y="49"/>
        <delta pt="6" x="0" y="49"/>
        <delta pt="7" x="0" y="49"/>
        <delta pt="8" x="0" y="49"/>
        <delta pt="9" x="0" y="48"/>
        <delta pt="10" x="0" y="49"/>
        <delta pt="11" x="0" y="47"/>
        <delta pt="12" x="0" y="49"/>
        <delta pt="13" x="0" y="0"/>
        <delta pt="14" x="0" y="0"/>
        <delta pt="15" x="0" y="0"/>
        <delta pt="16" x="0" y="0"/>
      </tuple>
      <tuple>
        <coord axis="wght" value="1.0"/>
        <coord axis="BNCE" value="1.0"/>
        <delta pt="2" x="0" y="-49"/>
        <delta pt="7" x="0" y="-49"/>
        <delta pt="8" x="0" y="-47"/>
      </tuple>
      <tuple>
        <coord axis="ital" value="1.0"/>
        <coord axis="wght" value="1.0"/>
        <coord axis="IRGL" value="1.0"/>
        <delta pt="0" x="40" y="0"/>
        <delta pt="1" x="21" y="0"/>
        <delta pt="2" x="0" y="3"/>
        <delta pt="3" x="0" y="10"/>
        <delta pt="4" x="0" y="-2"/>
        <delta pt="5" x="-23" y="-10"/>
        <delta pt="6" x="-30" y="-10"/>
        <delta pt="7" x="-12" y="-10"/>
        <delta pt="8" x="10" y="-18"/>
        <delta pt="9" x="20" y="-28"/>
        <delta pt="10" x="20" y="-32"/>
        <delta pt="11" x="20" y="-22"/>
        <delta pt="12" x="30" y="0"/>
        <delta pt="13" x="0" y="0"/>
        <delta pt="14" x="20" y="0"/>
        <delta pt="15" x="0" y="0"/>
        <delta pt="16" x="0" y="0"/>
      </tuple>
      <tuple>
        <coord axis="ital" value="1.0"/>
        <coord axis="wght" value="1.0"/>
        <coord axis="BNCE" value="-1.0"/>
        <delta pt="0" x="10" y="0"/>
        <delta pt="1" x="9" y="0"/>
        <delta pt="5" x="10" y="0"/>
        <delta pt="9" x="9" y="0"/>
        <delta pt="10" x="10" y="0"/>
      </tuple>
      <tuple>
        <coord axis="ital" value="1.0"/>
        <coord axis="wght" value="1.0"/>
        <coord axis="BNCE" value="1.0"/>
        <delta pt="0" x="-10" y="0"/>
        <delta pt="3" x="-10" y="0"/>
        <delta pt="4" x="-9" y="0"/>
        <delta pt="7" x="-10" y="0"/>
        <delta pt="11" x="-10" y="0"/>
        <delta pt="12" x="-9" y="0"/>
      </tuple>
    </glyphVariations>
```
</details>

<img width="766" alt="image" src="https://user-images.githubusercontent.com/45946693/177382639-768a03fc-9e6e-4dc8-a8f3-2f4d0d533853.png">

**Comment by davelab6** [comment]
@dberlow is going to post something soon about this. 

@ewa says that we ought to prefer axis names that make sense to non-expert font users, and "tracking" is an expert term of art; CSS WG in the 90s also had this preference and called it "letter spacing", but since that's different to this in the details, I think not using that term for the axis that does the same/similar thing is good. I believe "spacing" is the front running candidate.

**Comment by arrowtype** [comment]
"Spacing" sounds good to me! I do like how CSS tries to name properties to make sense on their own, rather than to adhere too much to tradition.

**Comment by arrowtype** [comment]
@dberlow's point about spacing being added to the left/right sides based on text alignment is a good one, too. I have so far added spacing evenly to both sides, as a compromise, so it can work well in center-aligned text, and acceptably (though not ideally) in left or right-aligned text. 

My thinking is that adding two axes for spacing may feel confusing or overwhelming to users, and most of the time when it matters, they will have a tracking function built into the text layout environment, anyway. I could be convinced otherwise, perhaps.

Certainly, though, I think a spacing "swing" axis would be useful to name and define at the same time as Spacing, regardless of whether all fonts that builds in spacing also build in swing.
