### ISSUE TITLE
Add Bounce (BNCE) axis

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/axisregistry#38]
Related to Issue #38 

## Description

The in-progress OFL [Shantell Sans](https://shantell-sans.arrowtype.com/) is a marker-style font that has a Bounce axis `BNCE` that causes letters to move a semi-random distance above and below the baseline, and thus having a "bouncy" baseline. This may be used to simulate handwriting, but is also an effect seen in graphic design more generally  (memorably on some [jazz records](https://fontsinuse.com/uses/25386/jazz-kaleidoscope-by-pete-brown-and-jonah-jon) and posters).

![image](https://user-images.githubusercontent.com/45946693/166855467-5f5436a4-6524-4463-ba61-b97c01785e22.png)

## Range

Default: `0` (no change from the baseline)
Max: `1000` (units of UPM grid of offset from baseline, assuming UPM of 1000 ... most Bounce axes wouldn’t have this extreme of a bounce, so this is a proposed maximum value, if we need that.)
Min: `-1000` (A reversal of the maximum)

The positive and negative values make more sense to see in a screen recording – it’s an axis particularly well-suited to animation:

https://user-images.githubusercontent.com/45946693/166831946-199ae976-1cb6-4dd1-8bf6-1f81a6b9d19e.mov

## Instances

- Normal – `BNCE` at 0 – An elided name, except in static subfamilies, to differentiate from full variable font family name
- Semibouncy – `BNCE` at approximately 50%
- Bouncy – `BNCE` at 100%
- There could also be a "Superbouncy" style name, for fonts that go more extreme.

**Comment by arrowtype** [comment]
What might be my next steps be here? Hoping to get these fonts finished and onboarded in the coming month or two. Thanks!

**Comment by arrowtype** [comment]
Do we need to complete this issue before I can successfully master a font for Google Fonts?

**Comment by davelab6** [comment]
A per mille of em range is interesting, but what is the reference glyph for Latin and which is the distance being measured?

Your instalces are given as %s and this suggests to me that per-mille ranging may not be ideal.

Overall, @vv-monsalve suggested that https://fonts.google.com/knowledge/glossary/casual_axis might work well for this, as it seems to fir the definition provided there. That works both like a percentage range and as a boolean: `0.00..1.00`

**Comment by arrowtype** [comment]
Thanks for the answers here, Dave! That makes sense.

Re: axis values in Bounce:

- First, it is important for there to be a negative as well as positive range here, as bouncing animations look much better if bouncing can happen in two directions, rather than just one. A negative to positive range allows a wavy effect, whereas a positive-only range just means going from a flat baseline to a bouncy baseline, and this can’t be repeated in the same way.
- The values in the case of Shantell Sans are actually based on maximum potential movement along the UMP grid. So, a bounce of `100` means that a few glyphs get close to 100 units of movement, while others are less to give a randomized appearance. I tested more and less movement, but this seemed to be a sweet spot.
- I am basically thinking of this as a “percentage” from minimum to maximum bounce, however. I slightly prefer a -100 to +100 range, because that implies that intermediate values are intended for use. On the contrary, I think that a "binary" or -1 to +1 range would imply that styles are really meant to be either 0 or 1, similar to how the Italic axis is often a binary thing. 
- If there is a logical preference for a -1 to +1 axis, however, I am not particularly opposed to it. I could see one advantage being that a -1 to +1 range may help clarify that the movement wasn't expected to be tied to or measured by the UPM grid.

**Comment by vv-monsalve** [comment]
> Your instalces are given as %s and this suggests to me that per-mille ranging may not be ideal.

> - I am basically thinking of this as a “percentage” from minimum to maximum bounce, however. I slightly prefer a -100 to +100 range, because that implies that intermediate values are intended for use.

Dave's comment is originated in the original range definitions (defined in per mile values). However, a percentage range would be best for this axis indeed. There would be a consensus that 100% means the highest bounce level while leaving it open for type designers to freely govern what that percentage means based on their fonts.

> Can families ship with axes that are wider than what is represented in instances?

If you mean the VF going wider in the range than the static instances, yes. We've had some VF going from 1 to 1000 in the weight axis for example.

> Specifically, I am considering cutting down on the number of instances.
>This would bring me back down from 108 instances in 9 static subfamilies to 48 instances

This has been part of the reasoning around registering axis without predefined fallbacks as they overpopulated the instantiated statics fonts, like in Recursive. The goal is to have per-family named styles.

So the axis would be defined like this:

```
#Bounce, base on https://github.com/arrowtype/shantell-sans
tag: "BNCE"
display_name: "Bounce"
min_value: -100
max_value: 100
default_value: 0
precision: 1
fallback {
  name: "Default"
  value: 0
fallback_only: false
description:
  "Translate glyphs up and down along the y axis to result in an "
  "uneven, bouncy baseline. The negative range, if used, should reflect 
  "positive translations to provide an animatable axis."
```

**Comment by arrowtype** [comment]
Awesome, this is all super helpful! Thanks so much for that explanation and feedback. Sounds good to me!

**Comment by davelab6** [comment]
> DC> The GF team need to review the axis proposal with you and finalize a decision about it; my guess that this will be in September.

Given a 10/1 launch date target, we need to get the family's axes all sorted in about the next 7 days, to push to internal systems the 2nd week, and then push the font the 3rd week and have it ready on prod to make public on the 4th week :) @arrowtype  joined a call today and said he'll be around and responsive to any requests in the coming weeks, and I just met with @evanwadams  and he agreed this is cutting it close but seems feasible, especially since (a) @vv-monsalve has made good progress on drafting an Axis Registration Protocol document and (b) @yanone is back from summer vacations and can help drive the onboarding double checking process that @arrowtype is already very familiar with, to start with. :)

> SN> it is important for there to be a negative as well as positive range

Agreed, I just met with Evan and after a priori saying this is surprising, after we looked at the font, he agreed with this

> VM> a percentage range would be best for this axis 

Agreed, I think its nice that there's a per mille coincidence for this family but any future family could have its max per mille movement more or less than that and still use -100..100 as the actual range on a percentage semantic basis.

> SN> @davelab6 Can families ship with axes that are wider than what is represented in instances? I think so...

Yes, for sure. In fact, the named instances in STAT tables are not currently being registered - as we see in @vv-monsalve 's example just above, it has only the default - since there's been a semantic scope creep on the `fallback` key that we are cutting back on, currently. Maybe in the future we'll add a different key to the registry for "axis default named instances" which families can use, append, or ignore, but that's not relevant to the current axis registration protocol. (This does however mean until that arrives, there will be (much) less static files in the GF ZIPs, since those are generated from the `fallback` keys.)

> Normal, Bouncy, ExtraBouncy

I discussed this with @evanwadams and we agreed that's better than the previous Normal, SemiBouncy, Bouncy; following the `SOFT` axis (Sharp, Soft, SuperSoft) then for 'percent semantics' axes, the axis max as a 100% value is the most extreme form, and the mid point 50% value should show the treatment the axis applies in full effect, and allow users to take it every further all the way to 100%. Possibly we could prefer SuperWhatever to ExtraWhatever, or perhaps ExtraWhatever is the default (like the `wght` axis default named styles) and SuperSoft was an exception to obtain the nice alliteration. 

So, if @arrowtype is good with the numeric definitions in @vv-monsalve 's protobuf sketch above, then I think we only have to finalize the short description for that file and then the longer GFK Glossary page's description (in a Google Doc with @elliotjaystocks) and its GFK illustration (also in collaboration with @elliotjaystocks, likely in Figma).

I propose this short description:

```
  "Shift glyphs up and down in the Y dimension, resulting in an "
  "uneven, bouncy baseline. The negative range, if used, should reflect 
  "opposite shifts to the positive range, to enable looping animation."
```
