### ISSUE TITLE
Transfer all issue from legacy central repo

### ISSUE THREAD

**Issue by davelab6** [googlefonts/axisregistry#5]
Not urgent but @RosaWagner pointed out we need to (alas manually) transfer all the axis registry related issues from 
- [x] https://github.com/google/fonts/issues?q=is%3Aissue+is%3Aopen+axis+registry+label%3A%22I+Axis+Registry%22
- [x] https://github.com/google/fonts/issues?q=is%3Aissue+is%3Aopen+label%3A"--+Requires+Axis+Registration%22 (see also this [spreadsheet](https://docs.google.com/spreadsheets/d/1_a-y0ybVM4PqPflyJj7gQ5xDL1RRIyGATp2rroFJJNA/edit?usp=sharing))

**Comment by felipesanches** [comment]
It may be possible to (at least partially) automate this task by using the github module available on gftools. I can take a look at that.

**Comment by felipesanches** [comment]
https://github.com/google/fonts/issues?q=is%3Aissue+is%3Aopen+label%3A%22--+Requires+Axis+Registration%22

These ones should not be closed, because they are of the type "Add/Upgrade some family". They should remain open, while a linked issue should be opened here describing the new axis that needs to be added to the registry before the family onboarding (or update) can proceed.

**Comment by davelab6** [comment]
https://github.com/MAARK/github-issue-voyager looks like it can automate this
