### ISSUE TITLE
Weekly auto releases

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/axisregistry#6]
It may be a nice idea to cut a new pypi release every week if there are changes to the .textproto files.

**Comment by m4rc1e** [comment]
Same could be done for gflanguages

**Comment by felipesanches** [comment]
I agree that we should release frequently. But I'd rather do it manually. I can add this to my weekly TO-DO list. Likely to be done on Thursdays prior to our weekly onboarding video call. Or even better, on Friday afternoons right after the call, so that there's a chance of collectively approving the update.

**Comment by felipesanches** [comment]
For instance, I think the recent "Wonky" axis name change discussed at #8 may be incorrect. So I may revert this before cutting a release. It seems reasonable to me that we humans should discuss these subtle things instead of delegating releases to automation bots ;-)
